# Generated by Django 3.2.6 on 2021-08-08 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav_stocks',
            name='comment',
        ),
    ]
