# Generated by Django 3.1.7 on 2021-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analytics', '0003_auto_20210730_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
    ]
