# Generated by Django 3.1.7 on 2021-07-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analytics', '0005_auto_20210730_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.FloatField(),
        ),
    ]
